### ISSUE TITLE
I got 'TypeError: __call__() takes exactly 5 arguments'

### ISSUE THREAD

**Issue by CaoZhongZ** [malor/cpython-lldb#1]
TypeError: __call__() takes exactly 5 arguments (6 given)

What happend? I'm using most updated xcode.

**Comment by malor** [comment]
Thanks for the bug report, @4pao!

I've been reworking this code lately and will upload the new version soon.

**Comment by malor** [comment]
I've kept this open because we don't run the tests on Mac OS. At the same time, we now cover a variety of different LLDB versions, and this is known to work correctly.
