### ISSUE TITLE
Verify that cpython-lldb works with Python extensions written in other languages (C/Rust/etc)

### ISSUE THREAD

**Issue by inevity** [malor/cpython-lldb#38]
If use c python extension or rust binding, will not show any stacktrace.

If only use the python language to programming, then we can use the cpython-lldb??

**Comment by inevity** [comment]
Just use debug-built python, and pyqt5 debug build(qt binary install by brew,no debug info).Now only 
type lookup PyObject ok, other comand show nothing .
```
(lldb) py-bt
No Python traceback found (symbols might be missing)!
(lldb) py-up
*** Oldest frame
(lldb) py-down
*** Newest frame
```

**Comment by malor** [comment]
If the extension is linked against libpython, then it _should_ work. _However_, that's not tested at the moment, and I have not personally tried to do that, so it might be broken.

Thank you for reporting this! I'll give it a try!

**Comment by malor** [comment]
https://github.com/malor/cpython-lldb/releases/tag/0.2.0 contains a test case that uses a C extension, so this is supposed to be working. If this is still broken for you, please re-open the bug and attach a repro script if possible.
