### ISSUE TITLE
Missing source code, file names, and line numbers

### ISSUE THREAD

**Issue by jdevries3133** [malor/cpython-lldb#45]
Given the following "main.py":

```python
def baz():
    input()

def bar():
    baz()

def foo():
    bar()

def main():
    foo()

main()
```

If I run the program in lldb, pause it at the `input()`, and run `py-bt`, I get the following:

```
Traceback (most recent call last):
  File "No value", line 3722304989, in No value
    <source code is not available>
  File "No value", line 0, in No value
    <source code is not available>
  File "No value", line 0, in No value
    <source code is not available>
  File "No value", line 11247072, in No value
    <source code is not available>
  File "No value", line 0, in No value
    <source code is not available>
```

I am not seeing this bug on 3.9, but I do get it on 3.10 and later. I haven't been able to bisect down to the exact commit because I'm on an ARM Mac. I'm am going to try to investigate a fix for this since I'd really like to use this tool, but any tips pointing me in the right direction are much appreciated!

**Comment by malor** [comment]
Thank for reporting this, Jack! Python 3.10 is not supported yet. I need to update the code to account for the changes introduced in https://www.python.org/dev/peps/pep-0626/

**Comment by malor** [comment]
This should be fixed in master. I'm planning to cut a new release as soon as CPython 3.10 is released.
